name: SJTMapTools
main: Psycle\SJTMapTools\SJTMapTools
version: 0.0.1
api: 1.0.0

commands:
    startpermit:
        description: "Start a new permit region using the player's current location"
        usage: "/startpermit [player]"
        permission: myplugin.example
    endpermit:
        description: "Finish a new permit region using the player's current location, defining the permit name in the process"
        usage: "/endpermit <permitname> [player]"
        permission: myplugin.example
    teleporttopermit:
        description: "Teleport player to a named permit region"
        usage: "/endpermit <permitname> [player]"
        permission: myplugin.example
