name: SJTMapTools
main: Psycle\SJTMapTools\SJTMapTools
version: 0.0.1
api: 1.0.0

commands:
    startregion:
        description: "Start a new region using the player's current location"
        usage: "/startregion [player]"
        permission: myplugin.example
    endregion:
        description: "Finish a new region using the player's current location, defining the region name"
        usage: "/endregion <regionname> [player]"
        permission: myplugin.example
    tptoregion:
        description: "Teleport player to a named region"
        usage: "/tptoregion <regionname> [player]"
        permission: myplugin.example
    deleteregion:
        description: "Delete a named region"
        usage: "/deleteregion <regionname> [player]"
        permission: myplugin.example
